FROM dev-registry.danybot.com/cypress-node-deb:1

COPY --chown=builder:builder . /home/builder/

ARG DEV_BUILD="False"

USER builder

RUN npm i && \
    npm run build
    # if ! dev npm prune for production else run cypress
    
CMD npx prisma db push --accept-data-loss && npm run start
