import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '@components/Navbar'
import {
  VStack,
  Text,
  Box,
  HStack,
  UnorderedList,
  ListItem,
  StackDivider,
  Spacer,
  Link,
  Stack,
} from '@chakra-ui/layout'
import { useTheme } from '@chakra-ui/react'
import { Theme } from '@chakra-ui/theme'
import Icon from '@chakra-ui/icon'
import { GiPaperBoat } from 'react-icons/gi'
import { Input } from '@chakra-ui/input'
import { FormControl } from '@chakra-ui/form-control'
import { Button, IconButton } from '@chakra-ui/button'
import {
  MdArrowForward,
  MdArrowForwardIos,
  MdArrowRight,
  MdSearch,
} from 'react-icons/md'
import { Avatar } from '@chakra-ui/avatar'

const Home: NextPage = () => {
  const theme : Theme = useTheme()

  const ShipWreck = (props: {
    shipName : string
  }) => {
    return (
      <HStack w="full">
        <Text>{props.shipName}</Text>
        <Spacer />
        <IconButton aria-label="Go to shipwreck" fontSize="lg" icon={<MdArrowForwardIos />} />
      </HStack>
    )
  }

  const Rescuer = (props: {
    picture? : string,
    name: string
  }) => {
    return (
      <VStack spacing={4}>
        <Avatar size="xl" src={props.picture} />
        <Link color="blue">{props.name}</Link>
      </VStack>
    )
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack minH="100vh" h="full">
        {/**
         * Box de bienvenue
         */}
        <VStack
          h="50vh"
          bgColor={theme.colors.blue[500]}
          w="full"
          justify="center"
          spacing={8}
        >
          <Text as={'h1'} fontSize="4xl" color={theme.colors.white}>
            Rechercher un sauvetage
          </Text>
          <FormControl width={{
              base: "80%",
              md: "50%"
            }}>
            <Stack direction={{
              base: "column",
              md: "row"
            }}> 
              <Input
                placeholder="Exemple : Marie"
                bgColor={theme.colors.gray[100]}
                type="text"
                onClick={() => console.log('')}
              />
              <IconButton aria-label="Search shipwreck" fontSize="xl" icon={<MdSearch />}></IconButton>
            </Stack>
          </FormControl>
        </VStack>
        {/**
         * Le naufrage du jour
         */}

        <VStack
          boxShadow="lg"
          bgColor={theme.colors.white}
          borderRadius={8}
          h="full"
          p={8}
        >
          <HStack>
            <Text as={'h2'} fontSize="4xl">
              Le naufrage du jour
            </Text>

            <Icon as={GiPaperBoat} fontSize="4xl"></Icon>
          </HStack>
          <Text p={8}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi illum
            optio adipiscif nam, sed natus? Minus eum voluptate quaerat
            repellendus, magnam deleniti ducimus itaque mollitia nulla odit!
            Inventore, velit ipsam. Quod consequuntur quasi rerum vel et numquam
            sit, obcaecati, dicta aliquid alias ab error perspiciatis. Quos
            ratione cumque minima eaque. Cum adipisci, praesentium facilis nobis
            modi reiciendis accusamus vero voluptates. Suscipit mollitia nam ad
            ex, magnam delectus doloribus consectetur, explicabo, incidunt quod
            quisquam vero officiis.
          </Text>

          <Button colorScheme="blue" alignSelf="end">
            En savoir plus
          </Button>
        </VStack>

        {/**
         * Recent shipwrecks
         */}
        <VStack
          boxShadow="lg"
          bgColor={theme.colors.white}
          borderRadius={8}
          h="full"
          p={8}
          w="full"
        >
          <Text alignSelf="start" fontSize="xl">
            Naufrages récents
          </Text>
          <VStack w="full" divider={<StackDivider borderColor="gray.200" />}>
            <ShipWreck shipName="Aaaaaaa"></ShipWreck>
            <ShipWreck shipName="Aaaaaaa"></ShipWreck>
            <ShipWreck shipName="Aaaaaaa"></ShipWreck>
            <ShipWreck shipName="Aaaaaaa"></ShipWreck>
          </VStack>
        </VStack>

        <VStack
          boxShadow="lg"
          bgColor={theme.colors.white}
          borderRadius={8}
          h="full"
          p={8}
          w="full"
          justify="center"
          spacing={8}
          

        >
          <Text fontSize="4xl">Les héros du jour</Text>
          <Stack
          spacing={24}
          direction={{
            base: "column",
            md:"row"
          }}
          >
            <Rescuer name="Test Test" />
            <Rescuer name="Test Test" />
            <Rescuer name="Test Test" />
            <Rescuer name="Test Test" />
          </Stack>
        </VStack>
      </VStack>
    </>
  )
}

export default Home
